/**
 * generated by Xtext
 */
package org.opendaylight.nemo.tool.eclipse.plugin.validation;

import org.opendaylight.nemo.tool.eclipse.plugin.validation.AbstractEditorValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EditorValidator extends AbstractEditorValidator {
}
