/*
 * generated by Xtext
 */
package org.opendaylight.nemo.tool.eclipse.plugin.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.opendaylight.nemo.tool.eclipse.plugin.services.EditorGrammarAccess;

public class EditorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private EditorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.opendaylight.nemo.tool.eclipse.plugin.parser.antlr.internal.InternalEditorParser createParser(XtextTokenStream stream) {
		return new org.opendaylight.nemo.tool.eclipse.plugin.parser.antlr.internal.InternalEditorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public EditorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(EditorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
