/**
 * generated by Xtext
 */
package org.opendaylight.nemo.tool.eclipse.plugin.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class EditorOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
