/*
 * generated by Xtext
 */
package org.opendaylight.nemo.tool.eclipse.plugin.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class EditorUiModule extends org.opendaylight.nemo.tool.eclipse.plugin.ui.AbstractEditorUiModule {
	public EditorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
