/*
 * generated by Xtext
 */
package org.opendaylight.nemo.tool.eclipse.plugin;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class EditorRuntimeModule extends org.opendaylight.nemo.tool.eclipse.plugin.AbstractEditorRuntimeModule {

}
